### ISSUE TITLE
Bug in widgets that allow selection from sets

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1012]
This is a problem that presented similarly when I attempted to use the "topics" taxonomy in creating "news" pages on 12/22 and with the "authors" taxonomy when I was creating "media / library" pages on 12/23.

**Comment by marycklein** [comment]
Here is the email I sent Brylie while I was still "in the moment" working with the "media / library" pages:


Cannot add authors when building new items in media library. Actually, the widget is just weirdly balky and inconsistent in working or not working. 

Sometimes: Initially the button “Choose a page” to select an author is completely dead. Then, if I try to “save draft,” it won’t let me because I’ve failed to fill in a required field. However, sometimes after it’s informed me of that failure, the “Choose a page” button then works and takes me to the “search” for an author page. Then — this page may or may not respond to my typing in the search field and attempts to choose a name from the list.

Sometimes: Nothing I do will let me get past the dead “Choose a page” button.


I had a similar frustrating problem in choosing “topics” for news items that I was building last night.

**Comment by brylie** [comment]
I put in a rule to slow down bots on the site, but it accidentally caused issues with Wagtail talking to the server. I've turned off this rule, so Wagtail should be working smoothly now.

**Comment by brylie** [comment]
Apologies for the collateral damage. I'll be more careful when battling the bots. Please let me know if the site is working for you as expected now.

**Comment by marycklein** [comment]
Thanks for figuring this out so quickly!

I’ve turned my attention from WF to two full days of cooking and baking. I’ll check this website fix a some point in the next 12 hours.

Thanks again!
m

**Comment by marycklein** [comment]
OK. This was indeed fixed to allow selection of an Author for a Magazine Article.

However . . .  

Cannot select a Topic for a News Item. That is, no response at all from "Choose a page (topic)"

Cannot select a Sponsor for an Event. That is, no response at all from "Choose a page" under Sponsor.

**Comment by brylie** [comment]
Ok, I took a look at the Wagtail admin and fixed an issue with the JavaScript. Go ahead and try again.

**Comment by marycklein** [comment]
Thanks for the quick work!

Both work great.

best
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
