### ISSUE TITLE
Cloudflare demo

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1022]
I would like to talk about what I think is the off-putting message this (attached) projects to potential human readership. I am concerned about having folks' repeated opening split -second (or longer) with our website each time they open it be a statement about a concern for security . . . I think this will make people worried about their own security visiting our site, even if the point is really that it's the security  of our site that we're worried about. 

I don't think it's a good look to be projecting worry publicly. One could say that we are projecting prudence, but I don't think that's the message most people will read into this. "Why is WF making "a thing" of this when other websites are not?"-- is a pretty normal reaction to this encounter, in my opinion.

Maybe there's a less intrusive-to-the-human-visiting-public way to set this up. ??  

![Image](https://github.com/WesternFriend/westernfriend.org/assets/44241543/7efd911a-d185-4fa5-b467-5dc6cd167061)

**Comment by brylie** [comment]
Closing this since we had a demo last week.
