### ISSUE TITLE
Events - public listing of multi-day events

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1026]
A multi-day "event" should remain publicly listed for the full duration of the event. Currently on our website, events are dropped from public listing after the first day of the multi-day period.

When to drop an event from our public listing:

If **no end date** is specified, then drop after start date

If **an end date is specified**, then drop after end date

**Comment by brylie** [comment]
Upcoming and ongoing events should now show on the Events listing page. I.e., if an event start date or end date is "today" or later it will now be listed correctly.

**Comment by marycklein** [comment]
Thanks for fixing this! This is great.
Now . . . one more thing . . . And I hope this isn't a "big ask," I just never know . . .

On the "listing" pages that show events, can you display both "start" and "end" dates for the viewing public? 

I realize looking at it now -- now that you answered my first request -- that the "continuing" items now look like obsolete items that I've just forgotten to take down . . .

**Comment by brylie** [comment]
Sure. Let's track that request in a separate issue. That way our work stays organized and it is easy to find references to relevant discussions.
