### ISSUE TITLE
Cannot add authors to Library/media items

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1029]
This has been slow / buggy before, but today it is just not working at all. In the past, sometimes, if it would not let me add "Author 1," it might let me add "Author 2," and then I could go back and delete the first (empty) one. But today, the "search" for "Choose person, meeting, or organization" author is not moving one bit when I type a term into the search field (a term I am certain is in our database) and then click "return." When this thing is working, I don't usually even need to click "return," it just starts serving up possibilities

![Image](https://github.com/WesternFriend/westernfriend.org/assets/44241543/c0341ec2-7765-48fa-97c0-22dd68d10fca)

.

**Comment by brylie** [comment]
I'm sorry for any inconvenience caused earlier. I've fixed the issue (see attached picture). Could you please try again and let me know if it's working now?
![Screenshot_20240124_082314](https://github.com/WesternFriend/westernfriend.org/assets/17307/4da7809d-221c-49b0-8ca3-cfbc96fc5627)

**Comment by marycklein** [comment]
This still is not working for me. At least not in Firefox. I think I want to log out of Firefox completely before I try this in Safari. Back in a few.

**Comment by marycklein** [comment]
Nope. Not working in Safari, either. I enter a term in the "search" field and hit "return" and get zero response.

**Comment by brylie** [comment]
I've tweaked a security setting and the form now works as expected. Let me know if it works correctly on your end :-)

**Comment by brylie** [comment]
Closing as this is now resolved
