### ISSUE TITLE
Events - "search" within "Wagtail Admin" in not working

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1032]
I am trying to locate old "Quaker camp" listings in our collection of "events." When I type any term into the search widget, I get an error page. Attached are two screenshots. First shows that I am searching for a term that is clearly on the page to be found. Second shows the error message I get.

![Image](https://github.com/WesternFriend/westernfriend.org/assets/44241543/2a2fd96e-d90d-4803-8927-3345d7bc8fcb)

![Image](https://github.com/WesternFriend/westernfriend.org/assets/44241543/b788f06a-0f52-4e74-9f6e-9f51a4b54659)

**Comment by brylie** [comment]
I have just fixed this issue. Please try again and let me know whether it works for you.
