### ISSUE TITLE
One-time PayPal payments - can't locate some via Wagtail admin

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1038]
PayPal sends reports of all payments we receive in our PayPal account via our website.
PayPal reports of "subscription" payments -- either magazine or repeating donation -- are clear
PayPal reports of "one-time" payments are murkier. These either come from purchases from our bookstore or from one-time donations.

In attached two screenshots, 
- order on 1/7/2024 was for books
- order on 2/3/2024 was for -- who knows?

On 2/18/2024, I deleted first screenshot from this message as it was not informative. Details from screenshot included in additional comment on 2/18/2024

**Comment by brylie** [comment]
I’ve added a ‘payment_id’ column search to the Bookstore orders page. Try searching for the PayPal payment ID of any uncertain payments.

If we can’t find them in Bookstore orders, I’m not sure from where they would originate.

**Comment by marycklein** [comment]
I'm trying to see if I can "search" more effectively on the Bookstore orders page now.

I am hampered by lack of listing of dates of transactions on our Bookstore orders page. That would help me find the same transaction listed there and in PayPal. 

TEST SEARCH ON "ALEXANDER"

- Last name "Alexander" appears in both places. I feel confident that both listings refer to the same transaction, but it would be comforting to see with my eyes that they both refer to the same date and/or to the same dollar amount. I see neither of those details in our bookstore listing.
- Bookstore listing does show this transaction is for books. Paypal merely shows that "1" was purchased.
- Paypal search does not recognize the "paypal payment ID" -- 94J2156699694325S -- listed for Alexander on our website.
- Paypal does display a "transaction ID" for Alexander on 2/12/2024 -- 5R113405UP410782V 


SEARCH ON 1/7/2024 ORDER FOR BOOKS, NOTED AT START OF THIS GITHUB ISSUE
Last name "Gonda" appears in both places
Bookstore listing shows this purchase was for book; paypal shows it was for "1"
Palpal search does not recognize bookstore's "paypal payment ID" -- 4F770723XJ356951H
Paypal displays a "transaction ID" for this transaction -- 3LS66237GC1874927

SEARCH ON 2/3/2024 ORDER FOR -- ? WHAT ? -- NOTED AT START OF THIS GITHUB ISSUE [screenshot attachment failure]
Last name "Kisling" is NOT listed in bookstore, nor is email of jakislin@outlook.com
Bookstore listing does NOT include this transaction; Paypal shows that "1" was purchased
No bookstore "paypal payment ID" to use for looking up this transaction on Paypa
Paypal displays a "transaction ID" for this transaction -- 2CE82327FG083221U

**Comment by marycklein** [comment]
I’m afraid I see no transaction ID numbers at all on any of the orders in our bookstore any more. There are no values for the search to search through. 
Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by brylie** [comment]
This change will only apply to new and riders since the previous orders didn’t record the transaction ID.

**Comment by marycklein** [comment]
OK. Thanks!
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
