### ISSUE TITLE
Site "search" - restructure and/or add help text for visitors

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1042]
I chose a bad example when I raised this concern the first time -- happening to think of a name to "search" that had not actually been "published," but only "saved."

The other day, I wanted to retrieve the "bio" from the end of some article we've published by Barbara Birch in recent years. There have been a few. Type "Barbara Birch" into our "search" widget, an you need to scroll through five pages of results before you get to an article. I do believe some people will give up before they find what they're looking for. I knew for sure it was in there.

Can we prioritize the types of pages the search widget displays at the start of its list? I think you've already told me that is too hard, but I want to ask again anyway. Could the new search function that Wagtail is bragging about in Wagtail 6.0 be of any additional help to us here.

Or . . . Plan B . . . Can we find a way to enter our search term so that the widget would understand our intention better? If we could do that, then maybe we could add some help text for site visitors.

**Comment by brylie** [comment]
Added help text.
