### ISSUE TITLE
Bookstore purchases - individual transaction display?

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1083]
Terrific that Wagtail Admin can now see listing of purchases by date. Also terrific that PayPal Transaction ID is consistent with the ID that PayPal itself reports.

Can we have a display of individual transactions that I could share with a customer? Previously, I've just been capturing screen shots of the transaction report that used to be created. Currently, it seems when going from the "listing" of all "store" transactions into an individual transaction, what I get is a form that allows me to modify the transaction, which is good. Previously, I got "display" of all transaction details, which was marginally useful. A more compact display would be ideal.

What would be useful is some sort of display that shows for an individual transaction:

- Date of purchase
- Purchaser info
- Recipient info
- Items purchased
- Amount paid

**Comment by brylie** [comment]
On the orders page, click the ellipsis symbol "..."

![Screenshot 2024-06-05 at 20 08 02](https://github.com/WesternFriend/westernfriend.org/assets/17307/c33aa124-1f78-4379-b72d-a4cfd6529df8)

The inspect view, while not perfect, looks like this:

![Screenshot 2024-06-05 at 20 08 59](https://github.com/WesternFriend/westernfriend.org/assets/17307/1f266bee-6fcd-4a17-b2ba-46dad287a863)

**Comment by brylie** [comment]
If the above looks good, as per our discussion in weekly meeting, we can close this issue :-)

**Comment by marycklein** [comment]
Yes, please close this. I already logged out.
Thanks!
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
