### ISSUE TITLE
New loop-dee-loop in adding author / contact

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1093]
A new set of annoying steps has crept into the "add contact" function. 

Can we make these go away?

Used to be, you would choose from the "contact" tab in the left navigation menu either person, meeting, or organization, and the system took you to a form where you could add a new contact of the variety you chose.

Now, when you get to the juncture where you would like to open that form and fill in the info, instead, the system ask you to choose the type of form you want to fill in -- and it only gives you one choice, which it offers based on how you got their from the left nav menu.

See screen shots attached.

![Image](https://github.com/WesternFriend/westernfriend.org/assets/44241543/ba5c8ffc-b01e-40da-9b05-909ba63a88cb)
![Image](https://github.com/WesternFriend/westernfriend.org/assets/44241543/b9528914-2a79-458d-a42a-031558b1bdb1)

**Comment by brylie** [comment]
I reported this issue to the Wagtail community and one of the core maintainers opened a bug report:

https://github.com/wagtail/wagtail/issues/11969

The issue was fixed recently and should be included in an upcoming release.

**Comment by marycklein** [comment]
Excellent.
m

Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by brylie** [comment]
This should be resolved in the latest Wagtail 6.2 release :-)

**Comment by marycklein** [comment]
Yay!
m

Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
