### ISSUE TITLE
Display multiple online worship on monthly meeting main page

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1094]
Was just called to my attention that, for monthly meetings that host more than one online worship time, the "main page" describing that meeting in the Directory of Meetings only displays one of those times.

Examples:
https://westernfriend.org/community/meetings/intermountain-yearly-meeting/arizona-half-yearly-meeting/pima-monthly-meeting/
https://westernfriend.org/community/meetings/pacific-yearly-meeting/college-park-quarterly/palo-alto-friends-meeting/

My favorite solution would be to add to the form for building the meeting's "main page" so that for each "worship time" listed, I am offered a field where I can add a link to any online worship associated with that particular worship time.

My less preferred solution is for the system to automatically find and display all instances of online worship for that meeting. Since most of these online worship times are redundant with their in-person worship times (hybrid meetings), that could create confusing results.

**Comment by brylie** [comment]
The Meeting Profile page now shows all online worship associated with the meetings:

![Screenshot 2024-07-13 at 10 02 36](https://github.com/user-attachments/assets/b301b062-123b-436f-b8a8-08a556146fed)

**Comment by marycklein** [comment]
Great! Thanks!
m

Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
