### ISSUE TITLE
Captcha blocking registration

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1102]
A magazine subscriber is having a lot of trouble setting up a login account.

I decided to set him up myself. I could not get through the Captcha. Tried 4-5 times in Firefox and 3-4 times in Safari. I believe I found all the stairs or buses or cars correctly at least once, but I got the feedback in screenshot attached each time.

![Image](https://github.com/user-attachments/assets/88db84b8-bb80-4f57-b3f5-21ed94c9fced)

**Comment by brylie** [comment]
Since the reCAPTCHA service is managed by Google, there isn't much I can change with the user experience. The alternatives would be to remove the reCAPTCHA from the form or find an alternative way to deter spam registrations.

**Comment by marycklein** [comment]
Maybe this was a coincidental hiccup in Google yesterday. I’ll try again.

We do need to have it be possible for people to register so that the paywall will work, obviously.

To be continued!
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by marycklein** [comment]
Between my first message about this and today, I was confronted by the Google "find the cars" captcha on another website and succeeded the first time -- which has always been my normal experience with that captcha -- well if 98% success is "normal." It rarely fails to work. Not 7-8 times in a row like it did for me the other day . . . 

I decided to try again just now, and it didn't even present me with the Google captcha. Just said I'd failed by clicking the "I'm not a robot" box incorrectly. See attached.

![Image](https://github.com/user-attachments/assets/c6186c8b-4baa-40d0-ab3c-40c471eb6cec)
