### ISSUE TITLE
Bronwen problem with WF website

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#1110]
Attached are two screenshots from Bronwen's following of Brylie's instructions for getting some diagnostic info about her difficulty in loading Western Friend website from her home in Merida, Yucatan.

Also below are notes she sent me in response to questions I asked her.

She has not yet replied to my question whether she's tried getting onto our website from a coffee shop or library.

**Note from Bronwen 9/4/2024:**

Next, this darned website issue. Very, very odd that this is the only site where the issue has happened (at least the only site that I recall it happening). If it happened with frequency on a variety of sites, sure, I'd understand it being a local network issue, but it doesn't. 

**Note from Bronwen 9/10/2024, in response to my inquiry about when this problem began:**

A vague guesstimate, lemme see ... I think I noticed it when I was looking for your photos of IMYM 2024, so late June for sure the website wasn't working for me. I don't recall the last time before that when I was on the site. For sure it was working properly when I was checking the online Worship offerings to update the PacYM database, but that was at the beginning of the year. So, some time between the beginning of the year and late June it went haywire. 
If pinpointing a date is important, do your analytics break down by country/region/city? While I'm sure others in Mexico are visiting the WF site from time to time, I'm likely to be the only one from Merida, Yucatan.

**![Image](https://github.com/user-attachments/assets/af581bdc-b886-46ac-8513-04a0110acc68)
![Image](https://github.com/user-attachments/assets/c91c68cb-bf6b-499c-bd0c-7acefe58d3f5)
**

**Comment by brylie** [comment]
It looks like Bronwen's computer, network, or ISP is blocking all of the sfo3.digitaloceanspaces.com assets. Note the error net::ERR_NAME_NOT_RESOLVED, which means that Bronwen's computer is not able to convert the name sfo3.digitaloceanspaces.com into a network address (IP address.) This means her computer cannot connect to the DigitalOcean server to download the static assets.

Here are some troubleshooting steps that might help establish a connection to Digital Ocean servers:

1. Flush the computer's DNS cache:
   - Open Command Prompt as administrator
   - Run `ipconfig /flushdns`
2. Change DNS servers:
   - Try using Google's public DNS (8.8.8.8 and 8.8.4.4)
   - [How to change DNS servers in Windows](https://developers.google.com/speed/public-dns/docs/using#windows)
3. Disable VPN/proxy:
   - If you're using a VPN or proxy, try disabling it temporarily
4. Check firewall/antivirus:
   - Temporarily disable your firewall and antivirus to see if they're blocking the connection
5. Use nslookup:
   - Open Command Prompt
   - Run `nslookup sfo3.digitaloceanspaces.com`
   - Check if it returns an IP address
7. Restart your router:
   - Sometimes a simple router restart can fix DNS issues

If none of these steps work, it may be necessary to contact your ISP.

**Comment by brylie** [comment]
Closing this issue after confirming it was resolved with Mary
