### ISSUE TITLE
Ensure that we can scan the new site for broken links

### ISSUE THREAD

**Issue by brylie** [WesternFriend/westernfriend.org#438]
Add and configure the Wagtail link-checker package so we can scan the site for broken links.

https://pypi.org/project/wagtail-linkchecker/

**Comment by marycklein** [comment]
We also want to scan for instances when other people's websites are failing to get redirected to our new website from our old URLs. 

We should notify "important" websites of our current URLs.

Brylie said 11/27/2023:
I think Piwik records which pages receive 404 not found errors so we can fix them.

**Comment by brylie** [comment]
Using Semonto for broken link scanning and uptime monitoring

https://semonto.com/
