### ISSUE TITLE
Design Tweek - Home page - space above footer

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#606]
Match vertical spacing immediately above and below "featured events" to the spacing used immediately above and below "featured articles"

Match vertical spacing between event cards and footer to spacing set above "featured events"

![Image](https://github.com/WesternFriend/WF-website/assets/44241543/1c7f8b12-a06d-473e-853f-d54791f25a86)

![Image](https://github.com/WesternFriend/WF-website/assets/44241543/dab85da1-9017-4f6c-a01a-8b5e056116d0)

**Comment by brylie** [comment]
@werberger, would you like to take this issue?

**Comment by Dovineowuor** [comment]
Is the issue resolved?

**Comment by Dovineowuor** [comment]
> Is the issue resolved?

I would like to work on it

**Comment by brylie** [comment]
Thanks @Dovineowuor, I've assigned you

**Comment by Dovineowuor** [comment]
Great one @brylie . Working on it

**Comment by Dovineowuor** [comment]
![Featured-events Proposed redesign](https://github.com/WesternFriend/WF-website/assets/70941806/9fde271e-2fb9-4852-9454-34cbbae16ca7)
![LAnding Page Redesign](https://github.com/WesternFriend/WF-website/assets/70941806/0f6d75e6-1505-4a4a-8290-b1daba52fc5c)

Hello @brylie and the Westernfriends dev team,
Find above attached is the proposed design of the featured events as per the issue requirements.
Looking forward to getting an approval and or update proposals before implementation on the website.
Thank you very much for your time and the opportunity working with you.

With Regards,
Dovine K.

**Comment by brylie** [comment]
The design looks good. Let's use one of the standard Bootstrap spacing utilities, such as `mt-5`

https://getbootstrap.com/docs/5.3/utilities/spacing/

**Comment by Dovineowuor** [comment]
Cool Noted.

**Comment by marycklein** [comment]
Hello! I have also noticed more recently that the "leading" / line-spacing on the title of an "event" -- when it runs onto two lines -- needs to be reduced. See screenshot from "preview" site

![Image](https://github.com/WesternFriend/WF-website/assets/44241543/cf26cbf8-ee68-4d8a-9fc8-ac3678ba5f46)

**Comment by Dovineowuor** [comment]
On it

**Comment by brylie** [comment]
@marycklein, please open a separate issue for the Event title line break spacing, so the discussion on this issue can remain focused on the footer spacing.

**Comment by marycklein** [comment]
OK

**Comment by brylie** [comment]
@Dovineowuor, is there a status update for this issue or should we unassign the issue so it can be picked up by someone else?

**Comment by Dovineowuor** [comment]
I hard a bad experience with my computer lately but the issue is sorted, i will clear it next business week. Sorry for the inconveniences caused
