### ISSUE TITLE
Magazine Articles - "subscribe for full access" button

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#861]
Move this button to end of "teaser" from article, rather than at the beginning.

**Comment by marycklein** [comment]
This will also help any confusion that might be created by having a "teaser" be a coherent complete statement. Emphasize that "there's more."

![Image](https://github.com/WesternFriend/WF-website/assets/44241543/f193224d-13dc-45a1-9383-bc9c9cbf4021)

**Comment by brylie** [comment]
Done.
