### ISSUE TITLE
Switch to Wagtail generic viewset and page viewset for model administration

### ISSUE THREAD

**Issue by brylie** [WesternFriend/westernfriend.org#938]
We currently use the Wagtail ModelAdmin for defining admin UIs for our models. However, we are getting the following deprecation notice:

> RemovedInWagtail60Warning: wagtail.contrib.modeladmin is deprecated. Use wagtail.snippets or the separate wagtail-modeladmin package instead.

## Task

Switch model admin definitions to ModelViewSet

## Resources
- https://github.com/wagtail/wagtail/discussions/10740
- https://docs.wagtail.org/en/stable/extending/generic_views.html#generic-views

**Comment by sim-codes** [comment]
Are there direction as to were `ModelAdmin` is used or I just have to search for them

**Comment by brylie** [comment]
The ModelAdmin definitions are currently found in files named ‘wagtail_hooks.py’ In most of the project applications, such as ‘magazine’ or ‘community’. We want to replace those with ‘ModelViewSet’s while preserving the admin menu structure, if possible.

**Comment by brylie** [comment]
Note: ModelViewSet is a new option, an alternative to Snippets, that was released in Wagtail 5.2, which we have upgraded to.

**Comment by GT-Codeur** [comment]
Hello @brylie , Please assign me this issue

**Comment by sim-codes** [comment]
I'm already working on it

**Comment by sim-codes** [comment]
Why don't you want to use `snippets`? the `ModelViewSet` did not support panel which is used in Tags and I can seem to find function/class i.e. `modeladmin_register` to register them.

https://docs.wagtail.org/en/stable/reference/contrib/modeladmin/migrating_to_snippets.html

**Comment by brylie** [comment]
Ok. Snippets sound fine. 

ModelViewSet just has a more Pythonic name that conveys its purpose and aligns with Django naming conventions. Snippets just seem semantically odd and we’re originally intended for a more niche use case, such as reusable tags as opposed to general purpose content management listings.

**Comment by brylie** [comment]
Actually, double check the following document which shows how to register the ModelViewSet:

https://docs.wagtail.org/en/stable/extending/generic_views.html#generic-views

**Comment by brylie** [comment]
Done! :-)
