### ISSUE TITLE
Reduce line spacing of "event" titles on home page

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#957]
Vertical spacing of event titles would be better here if it were a little tighter

![Image](https://github.com/WesternFriend/WF-website/assets/44241543/a9159f3c-7dbc-4647-b708-d59569f08c21)

.

**Comment by Jilesh980** [comment]
hi @brylie can i work on this and solve this issue, thank you..

**Comment by brylie** [comment]
Thanks @Jilesh980!
