### ISSUE TITLE
Tags show doubled in News Items

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#986]
I created this test news item 12/13/2023

The tag “experiment” is one I selected from list that was offered to me.

The tag “experiential” is one that I typed in new.

https://westernfriend.org/news/a-test-news-item/

Pics here show what I entered and what I got.

![Image](https://github.com/WesternFriend/westernfriend.org/assets/44241543/04606ab8-1aa8-40db-aafd-cda4a9516f96)

![Image](https://github.com/WesternFriend/westernfriend.org/assets/44241543/0cc5461b-f52c-4ee2-a465-bf673c20ffed)

**Comment by brylie** [comment]
During development we decided to allow tags with different capitalizations. That means you can use various uppercase and lowercase letters like in the examples you mentioned.
