### ISSUE TITLE
News Items to share taxonomies with media library

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#987]
Currently, for composing "ExtraExtra News" items, the form offers open text fields to designate "news type" and "news topic." I would find it more functional for several reasons to have these two designations be drawn from limited and transparent lists of options.

These designations could "share" taxonomy buckets with similar ones in "media library." In fact, I did some rewriting of taxonomy items before the launch with this in mind.

“news topic” in ExtraExtra can draw from “topic” in media library

“news type” in ExtraExtra can draw from “genre” in library

AND . . . "yearly meeting" should be a non-required designation for each news item; or even better, would there be some way to select from "meeting" bucket OR "organization" bucket? Maybe a link to "community" more generally, with some help text to the user to designate either "yearly meeting" or a "quaker org" . . . ?

These, from media library, are what I would like to use for both ExtraExtra and for media library:

![Image](https://github.com/WesternFriend/westernfriend.org/assets/44241543/768fea73-20bb-48ac-b924-5ae6ed946c17)

![Image](https://github.com/WesternFriend/westernfriend.org/assets/44241543/0bf72944-dce9-4ede-a78c-60e0a6282f74)

**Comment by brylie** [comment]
Closed by #997
