### ISSUE TITLE
Delete dead PayPal button from menu bar, please

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#991]
I set up a new PayPal “donate” page and added it to the website where I want it to show.

However, the old / disabled PayPal “donate” button remains in the menu bar.

I got the impression from you today that you had nothing to do with that button showing up in the menu bar, but now I think that there must be some code that you inserted somehow.

I do not see an option for me to delete this item from the menu bar via “settings” > “editing navigation menu”

**Comment by brylie** [comment]
There was a misunderstanding. I said the navigation bar button code was added by me while the Donate page was yours to maintain.

The navigation bar donate button has now been removed.
