### ISSUE TITLE
Highlight recipient v payer in bookstore order results

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/westernfriend.org#993]
It would be super helpful to have some early indication -- without needing to open "edit order" -- as to who the recipient of an order actually is. I fear that in the bustle of everything, remembering to open "edit order" with each order might be too easy to forget to do.

**Comment by marycklein** [comment]
here is the original customer email that brought this issue to my attention

![Image](https://github.com/WesternFriend/westernfriend.org/assets/44241543/f3554f7c-8f49-4c49-a2e1-186cb590d581)

**Comment by brylie** [comment]
Great idea! I'll make the **Bookstore order listing page** easier to use by adding recipient details.

Just to clarify about the customer **magazine subscription** email: PayPal takes care of all the subscription details, like shipping addresses, during sign-up. This means westernfriend.org only keeps the PayPal subscription ID and doesn't store any other subscriber information.

![Screenshot_20231220_171336](https://github.com/WesternFriend/westernfriend.org/assets/17307/b4c6eeed-6dad-4661-a190-6b441bbfb53b)

**Comment by brylie** [comment]
Great idea! I'll make the **Bookstore order listing page** easier to use by adding recipient details.

Just to clarify about the customer **magazine subscription** email: PayPal takes care of all the subscription details, like shipping addresses, during sign-up. This means westernfriend.org only keeps the PayPal subscription ID and doesn't store any other subscriber information.


![Screenshot_20231220_171336](https://github.com/WesternFriend/westernfriend.org/assets/17307/91dd3879-c618-45bd-a95b-52135766e9bd)
